$(".buttonHide").click(function(){
    $("img").hide();
});
$(".buttonShow").click(function(){
    $("img").show();
});
$(".buttonToggle").click(function(){
    $("img").toggle();
});
$(".buttonSlideUp").click(function(){
    $("img").slideUp();
});
$(".buttonSlideDown").click(function(){
    $("img").slideDown();
});
$(".buttonSlideToggle").click(function(){
    $("img").slideToggle();
});
$(".buttonFadeIn").click(function(){
    $("img").fadeIn();
});
$(".buttonFadeOut").click(function(){
    $("img").fadeOut();
});
$(".buttonFadeToggle").click(function(){
    $("img").fadeToggle();
});